# Generated by Django 2.1 on 2018-08-09 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_band', to='Music.Band'),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(related_name='album_genre', to='Music.Genre'),
        ),
        migrations.AlterField(
            model_name='album',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_label', to='Music.Label'),
        ),
        migrations.AlterField(
            model_name='band',
            name='musicians',
            field=models.ManyToManyField(related_name='band_musicians', to='Music.Musician'),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_album', to='Music.Album'),
        ),
    ]
