# Generated by Django 2.1 on 2018-08-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_auto_20180809_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
