# Generated by Django 2.1 on 2018-08-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0003_person_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='facepic',
        ),
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.FileField(blank=True, upload_to='images/'),
        ),
    ]
