# Generated by Django 2.0.7 on 2018-07-31 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('website', models.URLField(blank=True)),
            ],
            options={
                'ordering': ('first_name',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('prefix', models.CharField(blank=True, max_length=20)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('released', models.DateField()),
                ('asin', models.CharField(blank=True, max_length=100)),
                ('coverimage', models.FileField(upload_to='Movies')),
                ('review', models.TextField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('directors', models.ManyToManyField(to='Movies.Director')),
                ('genre', models.ManyToManyField(to='Movies.Genre')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('prefix', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('web', models.URLField(blank=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.Studio'),
        ),
    ]
