# Generated by Django 2.1 on 2018-08-07 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('birth_date', models.DateField()),
                ('website', models.URLField()),
                ('email_id', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('prefix', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True)),
                ('release_date', models.DateField()),
                ('cover_image', models.FileField(upload_to='images/')),
                ('review', models.TextField()),
                ('asin', models.CharField(max_length=50)),
                ('directors', models.ManyToManyField(related_name='moviedirector', to='Movies.Director')),
                ('genre', models.ManyToManyField(related_name='moviegenre', to='Movies.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('prefix', models.CharField(max_length=50)),
                ('website', models.URLField()),
                ('slug', models.SlugField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moviestudio', to='Movies.Studio'),
        ),
    ]
